config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :buttons, only: [:index, :show, :new, :create, :edit, :update]
  resources :threadings, only: [:index, :show, :new, :create, :edit, :update]
  resources :zippers, only: [:index, :show, :new, :create, :edit, :update]
  resources :rubbers, only: [:index, :show, :new, :create, :edit, :update]
  resources :labels, only: [:index, :show, :new, :create, :edit, :update]
  resources :fabrics, only: [:index, :show, :new, :create, :edit, :update]
  resources :articles, only: [:index, :show, :new, :create]

  resources :manifests, only: [:fabric, :add_fabric, :fabric_create,
                               :button, :add_button, :create_button,
                               :label, :add_label, :create_label,
                               :rubber, :add_rubber, :create_rubber,
                               :threading, :add_threading, :create_threading,
                               :zipper, :add_zipper, :create_zipper] do
    collection do
      get 'fabric'
      get 'add_fabric'
      post 'fabric_create'
      get 'button'
      get 'add_button'
      post 'button_create'
      get 'label'
      get 'add_label'
      post 'label_create'
      get 'rubber'
      get 'add_rubber'
      post 'rubber_create'
      get 'threading'
      get 'add_threading'
      post 'threading_create'
      get 'zipper'
      get 'add_zipper'
      post 'zipper_create'
    end
  end

  resources :clients, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/fabric.rb
class Fabric < ApplicationRecord
  has_many :fabric_manifests
  has_many :articles, through: :fabric_manifests

  validates :fabric, presence: true,
                     length: { minimum: 1 }
  validates :composition, presence: true,
                          length: { minimum: 3, maximum: 30 }
  validates :weigth, presence: true,
                     numericality: { greater_than: 0 }
  validates :color, presence: true,
                    length: { minimum: 1 }
  validates :measure, presence: true,
                      inclusion: { in: %w(kg meter) }
  validates_numericality_of :price, presence: true,
                                    greater_than: 0,
                                    less_than_or_equal_to: BigDecimal(10**8)
  validates_numericality_of :count, presence: true,
                                    greater_than: 0

  def add(plus, price)
    self.update(count: self.count + plus, price: price)
  end

  def substract(minus, price)
    self.update(count: self.count - minus, price: price)
  end
end

app/controllers/fabrics_controller.rb
class FabricsController < ApplicationController
  def index
    @fabrics = Fabric.all
  end

  def show
    @fabric = Fabric.find(params[:id])
  end

  def new
    @fabric = Fabric.new
  end

  def create
    @fabric = Fabric.new(clean_params)

    respond_to do |format|
      if @fabric.save
        format.html { redirect_to @fabric, notice: 'Fabric was successfully created.' }
        format.json { render :show, status: :created, location: @fabric }
      else
        format.html { render :new }
        format.json { render json: @fabric.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @fabric = Fabric.find(params[:id])
  end

  def update
    @fabric = Fabric.find(params[:id])
    if update_params[:substract] == 'on'
      @fabric.substract(update_params[:count].to_f, update_params[:price].to_d)
    else
      @fabric.add(update_params[:count].to_f, update_params[:price].to_d)
    end

    respond_to do |format|
      if @fabric
        format.html { redirect_to @fabric, notice: 'Button was successfully updated.' }
        format.json { render :show, status: :ok, location: @fabric }
      else
        format.html { render :edit }
        format.json { render json: @fabric.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def clean_params
    params.permit(:fabric, :composition, :weigth, :color, :measure, :price, :count)
  end

  def update_params
    params.permit(:substract, :count, :price)
  end
end

app/helpers/fabrics_helper.rb
module FabricsHelper
end

app/views/fabrics/_buttons.html.erb
<%= link_to 'Current Fabric', @fabric, class: 'btn btn-primary' %>
<%= link_to 'Show All Fabrics', fabrics_path, class: 'btn btn-success' %>

app/views/fabrics/_form.html.erb
<%= form_with(model: @fabric, local: true) do |form| %>
  <% if @fabric && @fabric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fabric.errors.count, "error") %> prohibited this fabric from being saved:</h2>

      <ul>
      <% @fabric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <input name="fabric" type="text" placeholder="Fabric" class="form-control">
  </div>
  <div class="form-group">
    <input name="composition" type="text" placeholder="Composition" class="form-control">
  </div>
  <div class="form-group">
    <input name="weigth" type="number" min="0" placeholder="Weigth" class="form-control">
  </div>
  <div class="form-group">
    <input name="color" type="text" placeholder="Color" class="form-control">
  </div>
  <div class="form-group">
    <input name="measure" type="text" placeholder="Kg / Meter" class="form-control">
  </div>
  <div class="form-group">
    <input name="price" type="text" placeholder="Price" class="form-control">
  </div>
  <div class="form-group">
    <input name="count" type="text" placeholder="Count" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/fabrics/edit.html.erb
<h1>Edit fabric <%= @fabric.id %> <%= @fabric.fabric %></h1>

<%= form_with(model: @fabric, local: true) do |form| %>
  <% if @fabric.errors.any? %>
    <div id="error_explanation" style="font-color: red;">
      <h2><%= pluralize(@fabric.errors.count, "error") %> prohibited this fabric from being saved:</h2>

      <ul>
      <% @fabric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Current price: <%= @fabric.price %></h3>
  <div class="form-group">
    <input name="price" type="text" value="<%= @fabric.price %>" class="form-control">
  </div>

  <h3>Current count <%= @fabric.count %></h3>
  <div class="form-group">
    <input name="count" type="text" placeholder="Count" class="form-control">
  </div>

  <div class="form-group">
    <input type="checkbox" name="substract"> Substract
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
    <%= render 'buttons', fabric: @fabric %>
  </div>
<% end %>

app/views/fabrics/index.html.erb
<h1>Fabrics</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Fabric</th>
      <th scope="col">Composition</th>
      <th scope="col">Weigth</th>
      <th scope="col">Color</th>
      <th scope="col">Measure</th>
      <th scope="col">Delivery date</th>
      <th scope="col">Count</th>
      <th scope="col">Price</th>
      <th scope="col">Edit count & price</th>
    </tr>
  </thead>
  <tbody>
    <% @fabrics.each do |fabric| %>
      <tr>
        <th scope="row"><%= link_to fabric.id, fabric %></th>
        <td><%= fabric.fabric %></td>
        <td><%= fabric.composition %></td>
        <td><%= fabric.weigth %></td>
        <td><%= fabric.color %></td>
        <td><%= fabric.measure %></td>
        <td><%= fabric.updated_at.nil? ? fabric.created_at.strftime("%Y-%m-%d") : fabric.updated_at.strftime("%Y-%m-%d") %></td>
        <td><%= fabric.count %></td>
        <td><%= fabric.price %></td>
        <td><%= link_to 'Edit count & price', edit_fabric_path(fabric), class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fabric', new_fabric_path, class: "btn btn-outline-dark" %>

app/views/fabrics/new.html.erb
<h1>New fabric</h1>

<%= render 'form', fabric: @fabric %>

<br>

<%= link_to 'Back', fabrics_path, class: "btn btn-outline-dark" %>

app/views/fabrics/show.html.erb
<h1>Fabric <%=@fabric.id %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Fabric</th>
      <th scope="col">Composition</th>
      <th scope="col">Weigth</th>
      <th scope="col">Color</th>
      <th scope="col">Measure</th>
      <th scope="col">Date of delivery</th>
      <th scope="col">Count</th>
      <th scope="col">Price</th>
      <th scope="col">Edit count & price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @fabric.fabric %></th>
      <td><%= @fabric.composition %></td>
      <td><%= @fabric.weigth %></td>
      <td><%= @fabric.color %></td>
      <td><%= @fabric.measure %></td>
      <td><%= @fabric.updated_at.nil? ? @fabric.created_at : @fabric.updated_at %></td>
      <td><%= @fabric.count %></td>
      <td><%= @fabric.price %></td>
      <td><%= link_to 'Edit count & price', edit_fabric_path(@fabric), class: 'btn btn-warning' %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'All fabrics', fabrics_path, class: "btn btn-outline-dark" %>