config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :buttons, only: [:index, :show, :new, :create, :edit, :update]
  resources :threadings, only: [:index, :show, :new, :create, :edit, :update]
  resources :zippers, only: [:index, :show, :new, :create, :edit, :update]
  resources :rubbers, only: [:index, :show, :new, :create, :edit, :update]
  resources :labels, only: [:index, :show, :new, :create, :edit, :update]
  resources :fabrics, only: [:index, :show, :new, :create, :edit, :update]
  resources :articles, only: [:index, :show, :new, :create]

  resources :manifests, only: [:fabric, :add_fabric, :fabric_create,
                               :button, :add_button, :create_button,
                               :label, :add_label, :create_label,
                               :rubber, :add_rubber, :create_rubber,
                               :threading, :add_threading, :create_threading,
                               :zipper, :add_zipper, :create_zipper] do
    collection do
      get 'fabric'
      get 'add_fabric'
      post 'fabric_create'
      get 'button'
      get 'add_button'
      post 'button_create'
      get 'label'
      get 'add_label'
      post 'label_create'
      get 'rubber'
      get 'add_rubber'
      post 'rubber_create'
      get 'threading'
      get 'add_threading'
      post 'threading_create'
      get 'zipper'
      get 'add_zipper'
      post 'zipper_create'
    end
  end

  resources :clients, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/threading.rb
class Threading < ApplicationRecord
  has_many :threading_manifests
  has_many :articles, through: :threading_manifests

  validates :color, presence: true,
                    length: { minimum: 1 }
  validates :count, presence: true,
                    numericality: { only_integer: true,
                                    greater_than_or_equal_to: 1 }

  def add(plus)
    self.update(count: self.count + plus)
  end

  def substract(minus)
    self.update(count: self.count - minus)
  end
end

app/controllers/threadings_controller.rb
class ThreadingsController < ApplicationController
  def index
    @threadings = Threading.all
  end

  def show
    @threading = Threading.find(params[:id])
  end

  def new
    @threading = Threading.new
  end

  def create
    @threading = Threading.new(clean_params)

    respond_to do |format|
      if @threading.save
        format.html { redirect_to @threading, notice: 'Button was successfully created.' }
        format.json { render :show, status: :created, location: @threading }
      else
        format.html { render :new }
        format.json { render json: @threading.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @threading = Threading.find(params[:id])
  end

  def update
    @threading = Threading.find(params[:id])
    update_params[:substract] == 'on' ? @threading.substract(update_params[:count].to_i) : @threading.add(update_params[:count].to_i)
    respond_to do |format|
      if @threading
        format.html { redirect_to @threading, notice: 'Threading was successfully updated.' }
        format.json { render :show, status: :ok, location: @threading }
      else
        format.html { render :edit }
        format.json { render json: @threading.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def clean_params
    params.permit(:color, :count)
  end

  def update_params
    params.permit(:count, :substract)
  end
end

app/views/threadings/_buttons.html.erb
<%= link_to 'Current threading', @threading, class: 'btn btn-primary' %>
<%= link_to 'Show all threadings', threadings_path, class: 'btn btn-success' %>

app/views/threadings/_form.html.erb
<%= form_with(model: @threading, local: true) do |form| %>
  <% if @threading && @threading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@threading.errors.count, "error") %> prohibited this threading from being saved:</h2>

      <ul>
      <% @threading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <input name="color" type="text" placeholder="Color" class="form-control">
  </div>
  <div class="form-group">
    <input name="count" type="number" min="1" placeholder="Count" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/threadings/edit.html.erb
<h1>Edit threading <%= @threading.id %> <%= @threading.color %></h1>
<h3>Current count <%= @threading.count %></h3>

<%= form_with(model: @threading, local: true) do |form| %>
  <% if @threading.errors.any? %>
    <div id="error_explanation" style="font-color: red;">
      <h2><%= pluralize(@threading.errors.count, "error") %> prohibited this threading from being saved:</h2>

      <ul>
      <% @threading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <input name="count" type="number" min="1" placeholder="Count" class="form-control">
  </div>

  <div class="form-group">
    <input type="checkbox" name="substract"> Substract
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
    <%= render 'buttons', threading: @threading %>
  </div>
<% end %>

app/views/threadings/index.html.erb
<h1>Threadings</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Threading color</th>
      <th scope="col">Count</th>
      <th scope="col">Threading count</th>
    </tr>
  </thead>
  <tbody>
    <% @threadings.each do |threading| %>
      <tr>
        <th scope="row"><%= link_to threading.id, threading %></th>
        <td><%= threading.color %></td>
        <td><%= threading.count %> meters</td>
        <td><%= link_to 'Edit count', edit_threading_path(threading), class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New threading', new_threading_path, class: "btn btn-outline-dark" %>

app/views/threadings/new.html.erb
<h1>New threading</h1>

<%= render 'form', threading: @threading %>

<br>

<%= link_to 'Back', threadings_path, class: "btn btn-outline-dark" %>

app/views/threadings/show.html.erb
<h1>Threading <%= @threading.id %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Threading color</th>
      <th scope="col">Count</th>
      <th scope="col">Edit count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @threading.color %></th>
      <td><%= @threading.count %> meters</td>
      <td><%= link_to 'Edit count', edit_threading_path(@threading), class: 'btn btn-warning' %></td>
    </tr>
  </tbody>
</table>
<p>
  <%= link_to 'All threadings', threadings_path, class: 'btn btn-info' %>
</p>