config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :buttons, only: [:index, :show, :new, :create, :edit, :update]
  resources :threadings, only: [:index, :show, :new, :create, :edit, :update]
  resources :zippers, only: [:index, :show, :new, :create, :edit, :update]
  resources :rubbers, only: [:index, :show, :new, :create, :edit, :update]
  resources :labels, only: [:index, :show, :new, :create, :edit, :update]
  resources :fabrics, only: [:index, :show, :new, :create, :edit, :update]
  resources :articles, only: [:index, :show, :new, :create]

  resources :manifests, only: [:fabric, :add_fabric, :fabric_create,
                               :button, :add_button, :create_button,
                               :label, :add_label, :create_label,
                               :rubber, :add_rubber, :create_rubber,
                               :threading, :add_threading, :create_threading,
                               :zipper, :add_zipper, :create_zipper] do
    collection do
      get 'fabric'
      get 'add_fabric'
      post 'fabric_create'
      get 'button'
      get 'add_button'
      post 'button_create'
      get 'label'
      get 'add_label'
      post 'label_create'
      get 'rubber'
      get 'add_rubber'
      post 'rubber_create'
      get 'threading'
      get 'add_threading'
      post 'threading_create'
      get 'zipper'
      get 'add_zipper'
      post 'zipper_create'
    end
  end

  resources :clients, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :orders

  validates :name, presence: true,
                   length: { minimum: 1 }
  validates :accountable_person, presence: true,
                                 length: { minimum: 1 }
  validates :bulstat, presence: false,
                      length: { minimum: 1 }
  validates :address, presence: true,
                      length: { minimum: 1 }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_params(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :updated, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def client_params
    params.permit(:name, :accountable_person, :bulstat, :address)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: @client, local: true) do |form| %>
  <% if @client && @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <input name="name" type="text" placeholder="Company name" class="form-control">
  </div>
  <div class="form-group">
    <input name="accountable_person" type="text" placeholder="Accountable person" class="form-control">
  </div>
  <div class="form-group">
    <input name="bulstat" type="text" placeholder="BULSTAT" class="form-control">
  </div>
  <div class="form-group">
    <input name="address" type="text" placeholder="Address" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Edit <%= @client.id %> <%= @client.name %></h1>

<%= render 'form', client: @client %>

<br>

<%= link_to "Back <%= @client.id %> <%= @client.name %>", client_path, class: "btn btn-outline-dark" %>
<%= link_to 'Back to all clients', clients_path, class: "btn btn-dark" %>

app/views/clients/index.html.erb
<h1>Clients</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Accountable Person</th>
      <th scope="col">BULSTAT</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.id %></td>
        <td><%= client.name %></td>
        <td><%= client.accountable_person %></td>
        <td><%= client.bulstat %></td>
        <td><%= client.address %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create client', new_client_path, class: 'btn btn-dark' %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form', client: @client %>

<br>

<%= link_to 'Back', clients_path, class: "btn btn-outline-dark" %>

app/views/clients/show.html.erb
<h1><%= @client.id %> <%= @client.name%></h1>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Company name</th>
      <th scope="col">Accountable person</th>
      <th scope="col">BULSTAT</th>
      <th scope="col">Address</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @client.name %></th>
      <td><%= @client.accountable_person %></td>
      <td><%= @client.bulstat %></td>
      <td><%= @client.address %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit client', edit_client_path(@client), class: 'btn btn-outline-warning' %>
<%= link_to 'Back to all clients', clients_path, class: "btn btn-outline-dark" %>