config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :buttons, only: [:index, :show, :new, :create, :edit, :update]
  resources :threadings, only: [:index, :show, :new, :create, :edit, :update]
  resources :zippers, only: [:index, :show, :new, :create, :edit, :update]
  resources :rubbers, only: [:index, :show, :new, :create, :edit, :update]
  resources :labels, only: [:index, :show, :new, :create, :edit, :update]
  resources :fabrics, only: [:index, :show, :new, :create, :edit, :update]
  resources :articles, only: [:index, :show, :new, :create]

  resources :manifests, only: [:fabric, :add_fabric, :fabric_create,
                               :button, :add_button, :create_button,
                               :label, :add_label, :create_label,
                               :rubber, :add_rubber, :create_rubber,
                               :threading, :add_threading, :create_threading,
                               :zipper, :add_zipper, :create_zipper] do
    collection do
      get 'fabric'
      get 'add_fabric'
      post 'fabric_create'
      get 'button'
      get 'add_button'
      post 'button_create'
      get 'label'
      get 'add_label'
      post 'label_create'
      get 'rubber'
      get 'add_rubber'
      post 'rubber_create'
      get 'threading'
      get 'add_threading'
      post 'threading_create'
      get 'zipper'
      get 'add_zipper'
      post 'zipper_create'
    end
  end

  resources :clients, only: [:index, :show, :new, :create, :edit, :update]
end

app/controllers/manifests_controller.rb
class ManifestsController < ApplicationController
  def fabric
    @article = Article.last
    @fabric_manifest = FabricManifest.new
  end

  def fabric_create
    @article = Article.last
    @fabric_manifest = FabricManifest.new(fabric_params)

    respond_to do |format|
      if @fabric_manifest.save
        format.html { redirect_to add_fabric_manifests_path, notice: 'Fabric manifest was successfully created.' }
      else
        format.html { render :fabric }
      end
    end
  end

  def add_fabric
    @article = Article.last
  end

  def button
    @article = Article.last
    @button = ButtonManifest.new
  end

  def button_create
    @article = Article.last
    @button_manifest = ButtonManifest.new(button_params)

    respond_to do |format|
      if @button_manifest.save
        format.html { redirect_to add_button_manifests_path, notice: 'Button manifest was successfully created.' }
      else
        format.html { render :button }
      end
    end
  end

  def add_button
    @article = Article.last
  end

  def label
    @article = Article.last
    @label = LabelManifest.new
  end

  def label_create
    @article = Article.last
    @label_manifest = LabelManifest.new(button_params)

    respond_to do |format|
      if @label_manifest.save
        format.html { redirect_to add_label_manifests_path, notice: 'Label manifest was successfully created.' }
      else
        format.html { render :label }
      end
    end
  end

  def add_label
    @article = Article.last
  end

  def rubber
    @article = Article.last
    @rubber = RubberManifest.new
  end

  def rubber_create
    @article = Article.last
    @rubber_manifest = RubberManifest.new(button_params)

    respond_to do |format|
      if @rubber_manifest.save
        format.html { redirect_to add_rubber_manifests_path, notice: 'Rubber manifest was successfully created.' }
      else
        format.html { render :rubber }
      end
    end
  end

  def add_rubber
    @article = Article.last
  end

  def threading
    @article = Article.last
    @threading = ThreadingManifest.new
  end

  def threading_create
    @article = Article.last
    @threading_manifest = ThreadingManifest.new(button_params)

    respond_to do |format|
      if @threading_manifest.save
        format.html { redirect_to add_threading_manifests_path, notice: 'Threading manifest was successfully created.' }
      else
        format.html { render :threading }
      end
    end
  end

  def add_threading
    @article = Article.last
  end

  def zipper
    @article = Article.last
    @zipper = ZipperManifest.new
  end

  def zipper_create
    @article = Article.last
    @zipper_manifest = ZipperManifest.new(button_params)

    respond_to do |format|
      if @zipper_manifest.save
        format.html { redirect_to add_zipper_manifests_path, notice: 'Zipper manifest was successfully created.' }
      else
        format.html { render :zipper }
      end
    end
  end

  def add_zipper
    @article = Article.last
  end

  private

  def fabric_params
    params.permit(:article_id, :fabric_id, :count)
  end

  def button_params
    params.permit(:article_id, :button_id, :count)
  end

  def label_params
    params.permit(:article_id, :label_id, :count)
  end

  def rubber_params
    params.permit(:article_id, :rubber_id, :count)
  end
end

app/helpers/manifests_helper.rb
module ManifestsHelper
end

app/views/manifests/add_button.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Button</th>
      <th scope="col">Size</th>
    </tr>
  </thead>
  <tbody>
    <% @article.button_manifests.each do |b_m| %>
      <% button = Button.find(b_m.button_id) %>
      <tr>
        <th scope="row"><%= button.id %></th>
        <td><%= button.type_of_button %></td>
        <td><%= b_m.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @article.button_manifests.count < 3 %>
  <%= link_to 'Add button', button_manifests_path, class: 'btn btn-outline-success' %>
<% end %>
<%= link_to 'Add label', label_manifests_path, class: 'btn btn-dark' %>

app/views/manifests/add_fabric.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Fabric</th>
      <th scope="col">Length</th>
    </tr>
  </thead>
  <tbody>
    <% @article.fabric_manifests.each do |f_m| %>
      <% fabric = Fabric.find(f_m.fabric_id) %>
      <tr>
        <th scope="row"><%= fabric.id %></th>
        <td><%= fabric.fabric %></td>
        <td><%= f_m.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @article.fabric_manifests.count < 3 %>
  <%= link_to 'Add fabric', fabric_manifests_path, class: 'btn btn-outline-success' %>
<% end %>
<%= link_to 'Add button', button_manifests_path, class: 'btn btn-dark' %>

app/views/manifests/add_label.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Label</th>
      <th scope="col">Length</th>
    </tr>
  </thead>
  <tbody>
    <% @article.label_manifests.each do |l_m| %>
      <% label = Label.find(l_m.label_id) %>
      <tr>
        <th scope="row"><%= label.id %></th>
        <td><%= label.measure %></td>
        <td><%= l_m.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @article.label_manifests.count < 3 %>
  <%= link_to 'Add label', label_manifests_path, class: 'btn btn-outline-success' %>
<% end %>
<%= link_to 'Add rubber', rubber_manifests_path, class: 'btn btn-dark' %>

app/views/manifests/add_rubber.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Rubber</th>
      <th scope="col">Width</th>
      <th scope="col">Length</th>
    </tr>
  </thead>
  <tbody>
    <% @article.rubber_manifests.each do |r_m| %>
      <% rubber = Rubber.find(r_m.rubber_id) %>
      <tr>
        <th scope="row"><%= rubber.id %></th>
        <td><%= rubber.color %></td>
        <td><%= rubber.width %></td>
        <td><%= r_m.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @article.rubber_manifests.count < 3 %>
  <%= link_to 'Add rubber', rubber_manifests_path, class: 'btn btn-outline-success' %>
<% end %>
<%= link_to 'Add threading', threading_manifests_path, class: 'btn btn-dark' %>

app/views/manifests/add_threading.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Threading</th>
      <th scope="col">Length</th>
    </tr>
  </thead>
  <tbody>
    <% @article.threading_manifests.each do |t_m| %>
      <% threading = Threading.find(t_m.label_id) %>
      <tr>
        <th scope="row"><%= threading.id %></th>
        <td><%= threading.color %></td>
        <td><%= t_m.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @article.threading_manifests.count < 3 %>
  <%= link_to 'Add threading', threading_manifests_path, class: 'btn btn-outline-success' %>
<% end %>
<%= link_to 'Add zipper', zipper_manifests_path, class: 'btn btn-dark' %>

app/views/manifests/add_zipper.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Zipper</th>
      <th scope="col">Length</th>
      <th scope="col">Length</th>
    </tr>
  </thead>
  <tbody>
    <% @article.zipper_manifests.each do |z_m| %>
      <% zipper = Zipper.find(z_m.rubber_id) %>
      <tr>
        <th scope="row"><%= zipper.id %></th>
        <td><%= zipper.name %></td>
        <td><%= zipper.zipper_length %></td>
        <td><%= z_m.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @article.zipper_manifests.count < 5 %>
  <%= link_to 'Add zipper', zipper_manifests_path, class: 'btn btn-outline-success' %>
<% end %>
<%= link_to 'Complete', article_path, class: 'btn btn-dark' %>

app/views/manifests/button.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>
<h2>New button manifests</h2>
<%= form_with url: button_create_manifests_path do |form| %>
  <% if @button_manifest && @button_manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@button_manifest.errors.count, "error") %> prohibited this button_manifest from being saved:</h2>

      <ul>
      <% @button_manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :article_id, value: @article.id %>

  <% button = Button.all %>

  <div class="form-group">
    <select name="button_id" class="custom-select">
      <% button.each do |b| %>
        <option value="<%= b.id %>"><%= b.type_of_button %></option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <input name="count" type="text" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/manifests/fabric.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>
<h2>New fabric manifests</h2>
<%= form_with url: fabric_create_manifests_path do |form| %>
  <% if @fabric_manifest && @fabric_manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fabric_manifest.errors.count, "error") %> prohibited this fabric_manifest from being saved:</h2>

      <ul>
      <% @fabric_manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :article_id, value: @article.id %>

  <% fabrics = Fabric.all %>

  <div class="form-group">
    <select name="fabric_id" class="custom-select">
      <% fabrics.each do |f| %>
        <option value="<%= f.id %>"><%= f.fabric %></option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <input name="count" type="text" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/manifests/label.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>
<h2>New label manifests</h2>
<%= form_with url: label_create_manifests_path do |form| %>
  <% if @label_manifest && @label_manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@label_manifest.errors.count, "error") %> prohibited this label_manifest from being saved:</h2>

      <ul>
      <% @label_manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :article_id, value: @article.id %>

  <% labels = Label.all %>

  <div class="form-group">
    <select name="label_id" class="custom-select">
      <% labels.each do |l| %>
        <option value="<%= l.id %>"><%= l.measure %></option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <input name="count" type="text" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/manifests/rubber.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>
<h2>New rubber manifests</h2>
<%= form_with url: rubber_create_manifests_path do |form| %>
  <% if @rubber_manifest && @rubber_manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubber_manifest.errors.count, "error") %> prohibited this rubber_manifest from being saved:</h2>

      <ul>
      <% @rubber_manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :article_id, value: @article.id %>

  <% rubbers = Rubber.all %>

  <div class="form-group">
    <select name="rubber_id" class="custom-select">
      <% rubbers.each do |r| %>
        <option value="<%= r.id %>"><%= r.color %> / <%= r.width %></option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <input name="count" type="text" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/manifests/threading.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>
<h2>New threading manifests</h2>
<%= form_with url: threading_create_manifests_path do |form| %>
  <% if @threading_manifest && @threading_manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@threading_manifest.errors.count, "error") %> prohibited this threading_manifest from being saved:</h2>

      <ul>
      <% @threading_manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :article_id, value: @article.id %>

  <% threadings = Threadings.all %>

  <div class="form-group">
    <select name="label_id" class="custom-select">
      <% threadings.each do |t| %>
        <option value="<%= t.id %>"><%= t.color %></option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <input name="count" type="text" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/manifests/zipper.html.erb
<h1><%= @article.id %> <%= @article.title %></h1>
<h2>New zipper manifests</h2>
<%= form_with url: zipper_create_manifests_path do |form| %>
  <% if @zipper_manifest && @zipper_manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zipper_manifest.errors.count, "error") %> prohibited this zipper_manifest from being saved:</h2>

      <ul>
      <% @zipper_manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :article_id, value: @article.id %>

  <% zippers = Zipper.all %>

  <div class="form-group">
    <select name="zipper_id" class="custom-select">
      <% zippers.each do |z| %>
        <option value="<%= z.id %>"><%= z.name %> / <%= z.zipper_length %></option>
      <% end %>
    </select>
  </div>

  <div class="form-group">
    <input name="count" type="text" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>